# Generated by Django 6.0.3 on 2026-03-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('category', models.CharField(choices=[('estudos', 'Estudos'), ('trabalho', 'Trabalho'), ('casa', 'Casa')], default='casa', max_length=20, verbose_name='Categoria')),
                ('completed', models.BooleanField(default=False, verbose_name='Concluída')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
